[env]
ENV_DIR = { source = "${CARGO_MAKE_PROFILE}", default_value = "debug", mapping = { release = "release" } }
CARGO_TARGET_DIR = { value = "target", condition = { env_not_set = ["CARGO_TARGET_DIR"] } }
CARGO_WASM_PATH = "${CARGO_TARGET_DIR}/web/wasm32-unknown-unknown/${ENV_DIR}/${CARGO_MAKE_CRATE_NAME}.wasm"
CARGO_PROFILE = "dev"
TARGET_DIR = "target"
CARGO_MANIFEST_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}"

[env.development]
CARGO_ARGS = "--features bevy/dynamic"

[env.release]
CARGO_RELEASE_ARGS = "--release"

[tasks.show-env]
command = "env"

[tasks.basic-http-server]
install_crate = { crate_name = "basic-http-server", binary = "basic-http-server", test_arg = "--help" }

[tasks.wasm-bindgen-cli]
install_crate = { crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen", test_arg = "--help" }
install_crate_args = ["--git", "https://github.com/rustwasm/wasm-bindgen", "--tag", "0.2.69", "wasm-bindgen-cli"]

[tasks.cargo-build-web]
env = { "CARGO_TARGET_DIR" = "${CARGO_TARGET_DIR}/web" }
args = ["build", "--target", "wasm32-unknown-unknown", "@@split(CARGO_RELEASE_ARGS, )"]
command = "cargo"

[tasks.build-web]
env = { "CARGO_TARGET_DIR" = "${CARGO_TARGET_DIR}/web" }
args = ["--out-dir", "${TARGET_DIR}", "--out-name", "wasm", "--target", "web", "--no-typescript", "${CARGO_WASM_PATH}"]
command = "wasm-bindgen"
dependencies = ["cargo-build-web", "wasm-bindgen-cli"]

[tasks.build-native]
env = { "CARGO_TARGET_DIR" = "${CARGO_TARGET_DIR}/native" }
args = ["build", "@@split(CARGO_ARGS, )", "@@split(CARGO_RELEASE_ARGS, )"]
command = "cargo"

[tasks.build-headless]
env = { "CARGO_TARGET_DIR" = "${CARGO_TARGET_DIR}/native" }
args = ["build", "@@split(CARGO_ARGS, )", "--features", "headless", "@@split(CARGO_RELEASE_ARGS, )"]
command = "cargo"

[tasks.headless]
env = { "CARGO_TARGET_DIR" = "${CARGO_TARGET_DIR}/native" }
command = "${CARGO_TARGET_DIR}/${ENV_DIR}/${CARGO_MAKE_BINARY_EXECUTABLE_NAME}"
dependencies = ["build-headless"]

[tasks.run]
command = "${CARGO_TARGET_DIR}/${ENV_DIR}/${CARGO_MAKE_BINARY_EXECUTABLE_NAME}"
dependencies = ["build-native"]

[tasks.serve]
command = "basic-http-server"
args = ["-x"]
dependencies = ["build-web", "basic-http-server"]

[tasks.test]
disabled = true
